# Generated by Django 2.1.5 on 2019-04-08 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20190408_0524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='avatars/default-avatar.png', upload_to='avatars/'),
        ),
    ]
