# Generated by Django 2.1.5 on 2019-05-14 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20190513_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='g_branch',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='g_cgpa',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='profile',
            name='g_college',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='profile',
            name='g_degree',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='g_year',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='profile',
            name='high_school',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='profile',
            name='hs_percentage',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='profile',
            name='hs_year',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='profile',
            name='pg_branch',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='pg_cgpa',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='profile',
            name='pg_college',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='profile',
            name='pg_degree',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='pg_year',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
