# Generated by Django 2.1.5 on 2019-05-15 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0013_auto_20190515_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFrameworks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('framework', models.CharField(blank=True, choices=[('J', 'Java'), ('P', 'Python'), ('C', 'C'), ('C++', 'C++')], max_length=3)),
                ('level', models.CharField(blank=True, choices=[('B', 'Beginner'), ('I', 'Intermediate'), ('A', 'Advance')], max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frameworks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.AlterField(
            model_name='userlanguage',
            name='language',
            field=models.CharField(blank=True, choices=[('J', 'Java'), ('P', 'Python'), ('C', 'C'), ('C++', 'C++')], max_length=3),
        ),
    ]
