# Generated by Django 2.1.5 on 2019-05-15 22:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0015_auto_20190515_2000'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPlatform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(blank=True, choices=[('AWS', 'Amazon Web Services'), ('ECL', 'Eclipse'), ('NTB', 'Netbeans'), ('HRU', 'Herokus')], max_length=3)),
                ('level', models.CharField(blank=True, choices=[('B', 'Beginner'), ('I', 'Intermediate'), ('A', 'Advance')], max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platforms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='userframework',
            name='framework',
            field=models.CharField(blank=True, choices=[('BTP', 'Bootstrap'), ('NG', 'Angular'), ('RCT', 'React'), ('Nod', 'NodeJS')], max_length=3),
        ),
    ]
