# Generated by Django 2.2.2 on 2019-06-08 11:56

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_auto_20190515_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=account.models.user_directory_path),
        ),
    ]
